Fix signature of onchange_company.
In our XML view we call it without arguments.  In commit
f9ecdc7eb40e1937deb590d86b122ba42d4a8381 we changed to match Odoo's signature
because we had an issue:

   TypeError: onchange_company() takes at most 5 arguments (8 given)

For some reason (maybe another view we have not fixed) Odoo was sending all
the arguments.

Since we're not calling `super` the solution seems to be flexible (this is no
longer used in Odoo 9+).  This is why I add another test: onchange_company
receives may positional args.

Fixes mercurio/xhg#23.

Fixes MERCURIO-1MA at https://sentry.lahavane.com/caraibes/mercurio/issues/5892